language: android
env:
    - TARGET=android-10 ABI=armeabi
    - TARGET=android-21 ABI=armeabi-v7a
before_install:
    - export TERM=dumb # to get clean gradle output
    - android list targets # for debugging
    - echo no | android create avd --force -n test -t $TARGET -b $ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - ./gradlew --daemon --stacktrace tasks # install dependencies while the eumulator is booting
    - android-wait-for-emulator
script:
    - export POWERASSERT_VERBOSE=2
    - ./gradlew --daemon --stacktrace build
    - # export COVERAGE=true
    - ./gradlew --daemon --stacktrace connectedCheck || (adb logcat -t 100 '*:E' && false)
after_script:
    - android delete avd -n test
